# Generated by Django 4.1.5 on 2023-01-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcategory', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idProduct', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=50)),
                ('price_unit_cop', models.FloatField()),
                ('placement', models.CharField(max_length=50)),
                ('del_date', models.DateField(auto_now_add=True, null=True)),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('idSubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategory.subcategory')),
            ],
        ),
    ]
