# Generated by Django 4.1.5 on 2023-02-04 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('supplier', '0001_initial'),
        ('product', '0001_initial'),
        ('lot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('idPurchase', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.IntegerField()),
                ('cost', models.FloatField()),
                ('note', models.CharField(max_length=50)),
                ('del_date', models.DateField(auto_now=True, null=True)),
                ('idLot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lot.lot')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('idSupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
