# Generated by Django 4.1.5 on 2023-01-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idPerson', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('idNumber', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('email_contact', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('del_date', models.DateField(auto_now_add=True, null=True)),
                ('date_create', models.DateField(auto_now=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('user_create', models.CharField(max_length=50)),
                ('user_update', models.CharField(max_length=50)),
                ('idLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
        ),
    ]
