# Generated by Django 4.1.5 on 2023-01-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('del_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('idCompany', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_contact', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
                ('settings_admin', models.TextField()),
                ('settings_user', models.TextField()),
                ('phone_contact', models.CharField(max_length=50)),
                ('cell_phone_contact', models.CharField(max_length=50)),
                ('email_contact', models.EmailField(max_length=254)),
                ('del_date', models.DateField(null=True)),
                ('date_create', models.DateField(auto_now=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('user_create', models.CharField(max_length=50)),
                ('user_update', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('idLocation', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('settings_admin', models.TextField()),
                ('settings_user', models.TextField()),
                ('phone_contact', models.CharField(max_length=50)),
                ('cell_phone', models.CharField(max_length=50)),
                ('email_contact', models.EmailField(max_length=254)),
                ('del_date', models.DateField(auto_now_add=True, null=True)),
                ('date_create', models.DateField(auto_now=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('user_create', models.CharField(max_length=50)),
                ('user_update', models.CharField(max_length=50)),
                ('idCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('idLot', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('del_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idPerson', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('idNumber', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('email_contact', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('del_date', models.DateField(auto_now_add=True, null=True)),
                ('date_create', models.DateField(auto_now=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('user_create', models.CharField(max_length=50)),
                ('user_update', models.CharField(max_length=50)),
                ('idLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idProduct', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=50)),
                ('price_unit_cop', models.FloatField()),
                ('placement', models.CharField(max_length=50)),
                ('del_date', models.DateField(auto_now_add=True, null=True)),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('idPurchase', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.IntegerField()),
                ('cost', models.FloatField()),
                ('note', models.CharField(max_length=50)),
                ('del_date', models.DateField(auto_now_add=True, null=True)),
                ('idLot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lot')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('idSupplier', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_company', models.CharField(max_length=50)),
                ('name_contact', models.CharField(max_length=50)),
                ('phone_contact', models.CharField(max_length=50)),
                ('whatsapp_contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('del_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('date_last_log', models.DateField()),
                ('role', models.CharField(max_length=50)),
                ('del_date', models.DateField(auto_now_add=True, null=True)),
                ('idPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('idSubCategory', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('del_date', models.DateField(auto_now_add=True, null=True)),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('idSale', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('del_date', models.DateField(auto_now_add=True, null=True)),
                ('idPurchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseSale',
            fields=[
                ('idPurchaseSale', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.IntegerField()),
                ('value', models.FloatField()),
                ('del_date', models.DateField(auto_now_add=True, null=True)),
                ('idLot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lot')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('idSale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sale')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='idSupplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='idSubCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategory'),
        ),
    ]
