# Generated by Django 4.1.5 on 2023-01-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('idSupplier', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_company', models.CharField(max_length=50)),
                ('name_contact', models.CharField(max_length=50)),
                ('phone_contact', models.CharField(max_length=50)),
                ('whatsapp_contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('del_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
