# Generated by Django 4.1.5 on 2023-02-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='del_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
