# Generated by Django 4.1.5 on 2023-02-04 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('idSale', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('del_date', models.DateField(auto_now=True, null=True)),
                ('idPurchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
